version: '2.4'

services:
  mysqldb:
    container_name: "mysqldb"
    image: mysql:8.0.22
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${MASTER_USER}"
      MYSQL_ROOT_PASSWORD: "${MASTER_PASSWORD}"
    volumes:
      - ./deployment/replica/mysql/conf/master.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_ROOT_PASSWORD
      interval: 3s
      timeout: 10s
      retries: 15
    ports:
      - 3336:3306
    networks:
      - infra

  backend:
    container_name: "backend"
    build:
      context: backend
    restart: always
    ports:
      - 8007:8080
    environment:
      JWT_SECRET: "${JWT_SECRET}"
      DB_HOST: "mysqldb"
      DB_USER: "${MASTER_USER}"
      DB_PASSWORD: "${MASTER_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      BUS_DSN: "${BUS_DSN}"
      BUS_TOPIC: "${BUS_TOPIC}"
      DEBUG: "${DEBUG}"
      NEWS_TOKEN: "${NEWS_TOKEN}"
      NEWS_URL: "http://news:${NEWS_PORT}"
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - infra

  frontend:
    container_name: "frontend"
    build:
      context: frontend
    restart: always
    ports:
      - 8008:80
    networks:
      - infra

networks:
  infra:
    name: infra
    external: true